name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: SaktiDwiCahyonoResume.tex
          working_directory: .
      - name: Add and commit pdf file
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'SaktiDwiCahyonoResume.pdf'
      
          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Sakti Dwi Cahyono
      
          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_email: saktidc@outlook.com
      
          # The message for the commit
          # Default: 'Commit from GitHub Actions'
          message: 'Update pdf file'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged