name: Build PDF
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: SaktiDwiCahyonoResume.tex
          working_directory: .
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: SaktiDwiCahyonoResume.pdf
          path: ./SaktiDwiCahyonoResume.pdf
        if: always()